export const APP_WEBINAR_SET_SLIDES = 'APP_WEBINAR_SET_SLIDES'
export const APP_WEBINAR_CLEAR_SLIDES = 'APP_WEBINAR_CLEAR_SLIDES'
export const APP_WEBINAR_SET_PAGINATION = 'APP_WEBINAR_SET_PAGINATION'
