export const APP_BANNER_GET = 'APP_BANNER_GET'
export const APP_BANNER_POST = 'APP_BANNER_POST'
export const APP_BANNER_UPDATE = 'APP_BANNER_UPDATE'
export const APP_BANNER_DELETE = 'APP_BANNER_DELETE'
